-- ============================================================
-- verify_schema.sql — GENERATO, non modificare a mano.
--   rigenera con: node supabase/tools/gen_verify_schema.mjs
--
-- Incolla tutto nel SQL Editor di Supabase ed esegui.
--
--   NESSUNA RIGA  = il database ha tutti gli oggetti che il repo dichiara.
--   QUALCHE RIGA  = quegli oggetti mancano, cioè una migration non è mai
--                   stata eseguita. La colonna "manca" dice cosa, e il
--                   nome di solito dice anche quale file cercare in
--                   supabase/migrations/.
--
-- Verifica la PRESENZA, non il contenuto: una funzione presente ma rimasta
-- a una versione vecchia non compare qui. Serve a intercettare la migration
-- saltata, che è l'errore che il workflow manuale produce davvero.
--
-- Le colonne di una tabella mancante non vengono elencate: si vedrebbe
-- l'intera tabella riga per riga, e la riga 'tabella' dice già tutto.
--
-- Oggetti attesi: 31 tabelle, 266 colonne, 78 funzioni, 20 trigger.
-- ============================================================

WITH attesi(tipo, oggetto) AS (VALUES
('tabella',  'ai_import_logs'),
('tabella',  'chain_disputes'),
('tabella',  'chain_messages'),
('tabella',  'chain_participants'),
('tabella',  'chain_proposals'),
('tabella',  'chat_messages'),
('tabella',  'fb_account_links'),
('tabella',  'fb_link_codes'),
('tabella',  'fb_sessions'),
('tabella',  'listing_ai_scores'),
('tabella',  'listing_images'),
('tabella',  'listing_pings'),
('tabella',  'listing_questions'),
('tabella',  'listing_secrets'),
('tabella',  'listing_translations'),
('tabella',  'listings'),
('tabella',  'match_snapshots'),
('tabella',  'matches'),
('tabella',  'notifications'),
('tabella',  'offers'),
('tabella',  'payment_declarations'),
('tabella',  'profiles'),
('tabella',  'push_tokens'),
('tabella',  'report_action_tokens'),
('tabella',  'reports'),
('tabella',  'saved_listings'),
('tabella',  'saved_search_matches'),
('tabella',  'saved_searches'),
('tabella',  'transaction_ratings'),
('tabella',  'transactions'),
('tabella',  'trust_audit'),
('colonna',  'ai_import_logs.created_at'),
('colonna',  'ai_import_logs.id'),
('colonna',  'ai_import_logs.listing_id'),
('colonna',  'ai_import_logs.parsed'),
('colonna',  'ai_import_logs.raw_payload'),
('colonna',  'ai_import_logs.source'),
('colonna',  'ai_import_logs.user_id'),
('colonna',  'chain_disputes.accused_id'),
('colonna',  'chain_disputes.chain_id'),
('colonna',  'chain_disputes.created_at'),
('colonna',  'chain_disputes.id'),
('colonna',  'chain_disputes.reason'),
('colonna',  'chain_disputes.reporter_id'),
('colonna',  'chain_disputes.resolution'),
('colonna',  'chain_disputes.resolution_note'),
('colonna',  'chain_disputes.resolved_at'),
('colonna',  'chain_messages.body'),
('colonna',  'chain_messages.chain_id'),
('colonna',  'chain_messages.created_at'),
('colonna',  'chain_messages.id'),
('colonna',  'chain_messages.read_at'),
('colonna',  'chain_messages.sender_id'),
('colonna',  'chain_participants.chain_id'),
('colonna',  'chain_participants.confirmed'),
('colonna',  'chain_participants.confirmed_at'),
('colonna',  'chain_participants.give_listing_id'),
('colonna',  'chain_participants.id'),
('colonna',  'chain_participants.position'),
('colonna',  'chain_participants.receive_listing_id'),
('colonna',  'chain_participants.user_id'),
('colonna',  'chain_proposals.canceled_reason'),
('colonna',  'chain_proposals.completed_at'),
('colonna',  'chain_proposals.created_at'),
('colonna',  'chain_proposals.expires_at'),
('colonna',  'chain_proposals.explanation'),
('colonna',  'chain_proposals.id'),
('colonna',  'chain_proposals.reminder_sent_at'),
('colonna',  'chain_proposals.status'),
('colonna',  'chat_messages.body'),
('colonna',  'chat_messages.created_at'),
('colonna',  'chat_messages.id'),
('colonna',  'chat_messages.offer_id'),
('colonna',  'chat_messages.read_at'),
('colonna',  'chat_messages.sender_id'),
('colonna',  'fb_account_links.linked_at'),
('colonna',  'fb_account_links.sender_id'),
('colonna',  'fb_account_links.user_id'),
('colonna',  'fb_link_codes.code'),
('colonna',  'fb_link_codes.created_at'),
('colonna',  'fb_link_codes.expires_at'),
('colonna',  'fb_link_codes.used_at'),
('colonna',  'fb_link_codes.user_id'),
('colonna',  'fb_sessions.payload'),
('colonna',  'fb_sessions.sender_id'),
('colonna',  'fb_sessions.updated_at'),
('colonna',  'listing_ai_scores.created_at'),
('colonna',  'listing_ai_scores.id'),
('colonna',  'listing_ai_scores.listing_id'),
('colonna',  'listing_ai_scores.payload'),
('colonna',  'listing_ai_scores.reliability'),
('colonna',  'listing_images.id'),
('colonna',  'listing_images.listing_id'),
('colonna',  'listing_images.position'),
('colonna',  'listing_images.url'),
('colonna',  'listing_pings.created_at'),
('colonna',  'listing_pings.from_listing_id'),
('colonna',  'listing_pings.id'),
('colonna',  'listing_pings.sender_id'),
('colonna',  'listing_pings.to_listing_id'),
('colonna',  'listing_questions.answer'),
('colonna',  'listing_questions.answered_at'),
('colonna',  'listing_questions.asker_id'),
('colonna',  'listing_questions.code'),
('colonna',  'listing_questions.created_at'),
('colonna',  'listing_questions.id'),
('colonna',  'listing_questions.listing_id'),
('colonna',  'listing_questions.lo'),
('colonna',  'listing_questions.stessa'),
('colonna',  'listing_secrets.listing_id'),
('colonna',  'listing_secrets.pnr'),
('colonna',  'listing_translations.description_translated'),
('colonna',  'listing_translations.lang'),
('colonna',  'listing_translations.listing_id'),
('colonna',  'listing_translations.provider'),
('colonna',  'listing_translations.title_translated'),
('colonna',  'listing_translations.updated_at'),
('colonna',  'listings.accepts_swap'),
('colonna',  'listings.ai_reliability'),
('colonna',  'listings.ai_reliability_expl'),
('colonna',  'listings.ai_reliability_updated_at'),
('colonna',  'listings.arrive_at'),
('colonna',  'listings.cerco_vendo'),
('colonna',  'listings.check_in'),
('colonna',  'listings.check_out'),
('colonna',  'listings.contact_url'),
('colonna',  'listings.created_at'),
('colonna',  'listings.currency'),
('colonna',  'listings.depart_at'),
('colonna',  'listings.description'),
('colonna',  'listings.dynamic_pricing_enabled'),
('colonna',  'listings.external_id'),
('colonna',  'listings.fare_type'),
('colonna',  'listings.gender'),
('colonna',  'listings.id'),
('colonna',  'listings.image_url'),
('colonna',  'listings.is_named_ticket'),
('colonna',  'listings.list_price'),
('colonna',  'listings.location'),
('colonna',  'listings.name_change_allowed'),
('colonna',  'listings.name_change_source'),
('colonna',  'listings.operator'),
('colonna',  'listings.pnr_fingerprint'),
('colonna',  'listings.price'),
('colonna',  'listings.price_floor'),
('colonna',  'listings.published_at'),
('colonna',  'listings.purchase_price'),
('colonna',  'listings.route_from'),
('colonna',  'listings.route_to'),
('colonna',  'listings.source'),
('colonna',  'listings.start_date'),
('colonna',  'listings.status'),
('colonna',  'listings.swap_wanted'),
('colonna',  'listings.ticket_class'),
('colonna',  'listings.title'),
('colonna',  'listings.trust_pending_at'),
('colonna',  'listings.trust_score'),
('colonna',  'listings.type'),
('colonna',  'listings.updated_at'),
('colonna',  'listings.user_id'),
('colonna',  'match_snapshots.generated_at'),
('colonna',  'match_snapshots.id'),
('colonna',  'match_snapshots.items'),
('colonna',  'match_snapshots.user_id'),
('colonna',  'matches.bidirectional'),
('colonna',  'matches.created_at'),
('colonna',  'matches.dims'),
('colonna',  'matches.explanation'),
('colonna',  'matches.from_listing_id'),
('colonna',  'matches.generated_at'),
('colonna',  'matches.id'),
('colonna',  'matches.items'),
('colonna',  'matches.model'),
('colonna',  'matches.score'),
('colonna',  'matches.to_listing_id'),
('colonna',  'matches.updated_at'),
('colonna',  'matches.user_id'),
('colonna',  'notifications.body'),
('colonna',  'notifications.created_at'),
('colonna',  'notifications.data'),
('colonna',  'notifications.id'),
('colonna',  'notifications.title'),
('colonna',  'notifications.type'),
('colonna',  'notifications.user_id'),
('colonna',  'offers.accepted_at'),
('colonna',  'offers.amount'),
('colonna',  'offers.cancel_reason'),
('colonna',  'offers.cancelled_by'),
('colonna',  'offers.confirm_reminder_sent_at'),
('colonna',  'offers.created_at'),
('colonna',  'offers.currency'),
('colonna',  'offers.dispute_reason'),
('colonna',  'offers.disputed_at'),
('colonna',  'offers.disputed_by'),
('colonna',  'offers.expires_at'),
('colonna',  'offers.finalized_at'),
('colonna',  'offers.from_listing_id'),
('colonna',  'offers.id'),
('colonna',  'offers.message'),
('colonna',  'offers.owner_confirmed_at'),
('colonna',  'offers.proposer_confirmed_at'),
('colonna',  'offers.proposer_id'),
('colonna',  'offers.rating_reminder_sent_at'),
('colonna',  'offers.reservation_expires_at'),
('colonna',  'offers.seen_by_proposer'),
('colonna',  'offers.status'),
('colonna',  'offers.suspicious_cancel_at'),
('colonna',  'offers.to_listing_id'),
('colonna',  'offers.type'),
('colonna',  'offers.updated_at'),
('colonna',  'payment_declarations.amount'),
('colonna',  'payment_declarations.created_at'),
('colonna',  'payment_declarations.currency'),
('colonna',  'payment_declarations.id'),
('colonna',  'payment_declarations.il'),
('colonna',  'payment_declarations.method'),
('colonna',  'payment_declarations.non'),
('colonna',  'payment_declarations.offer_id'),
('colonna',  'payment_declarations.paid_at'),
('colonna',  'payment_declarations.updated_at'),
('colonna',  'payment_declarations.user_id'),
('colonna',  'profiles.avatar_url'),
('colonna',  'profiles.bio'),
('colonna',  'profiles.counters'),
('colonna',  'profiles.created_at'),
('colonna',  'profiles.deleted_at'),
('colonna',  'profiles.email'),
('colonna',  'profiles.email_verified'),
('colonna',  'profiles.full_name'),
('colonna',  'profiles.id'),
('colonna',  'profiles.phone'),
('colonna',  'profiles.prefs'),
('colonna',  'profiles.terms_accepted_at'),
('colonna',  'profiles.terms_version'),
('colonna',  'profiles.updated_at'),
('colonna',  'profiles.username'),
('colonna',  'push_tokens.platform'),
('colonna',  'push_tokens.token'),
('colonna',  'push_tokens.updated_at'),
('colonna',  'push_tokens.user_id'),
('colonna',  'report_action_tokens.action'),
('colonna',  'report_action_tokens.created_at'),
('colonna',  'report_action_tokens.expires_at'),
('colonna',  'report_action_tokens.listing_id'),
('colonna',  'report_action_tokens.report_id'),
('colonna',  'report_action_tokens.token'),
('colonna',  'report_action_tokens.used_at'),
('colonna',  'reports.created_at'),
('colonna',  'reports.details'),
('colonna',  'reports.id'),
('colonna',  'reports.listing_id'),
('colonna',  'reports.reason'),
('colonna',  'reports.reported_user_id'),
('colonna',  'reports.reporter_id'),
('colonna',  'reports.status'),
('colonna',  'saved_listings.created_at'),
('colonna',  'saved_listings.listing_id'),
('colonna',  'saved_listings.user_id'),
('colonna',  'saved_search_matches.id'),
('colonna',  'saved_search_matches.listing_id'),
('colonna',  'saved_search_matches.matched_at'),
('colonna',  'saved_search_matches.saved_search_id'),
('colonna',  'saved_search_matches.seen'),
('colonna',  'saved_searches.active'),
('colonna',  'saved_searches.cerco_vendo'),
('colonna',  'saved_searches.created_at'),
('colonna',  'saved_searches.id'),
('colonna',  'saved_searches.location'),
('colonna',  'saved_searches.max_price'),
('colonna',  'saved_searches.route_from'),
('colonna',  'saved_searches.route_to'),
('colonna',  'saved_searches.type'),
('colonna',  'saved_searches.user_id'),
('colonna',  'transaction_ratings.chain_id'),
('colonna',  'transaction_ratings.created_at'),
('colonna',  'transaction_ratings.id'),
('colonna',  'transaction_ratings.offer_id'),
('colonna',  'transaction_ratings.rated_id'),
('colonna',  'transaction_ratings.rater_id'),
('colonna',  'transaction_ratings.stars'),
('colonna',  'transactions.buyer_id'),
('colonna',  'transactions.created_at'),
('colonna',  'transactions.id'),
('colonna',  'transactions.listing_id'),
('colonna',  'transactions.price'),
('colonna',  'transactions.seller_id'),
('colonna',  'transactions.status'),
('colonna',  'transactions.ttype'),
('colonna',  'trust_audit.created_at'),
('colonna',  'trust_audit.flags'),
('colonna',  'trust_audit.id'),
('colonna',  'trust_audit.listing_id'),
('colonna',  'trust_audit.raw'),
('colonna',  'trust_audit.sub_scores'),
('colonna',  'trust_audit.suggested_fixes'),
('colonna',  'trust_audit.trust_score'),
('colonna',  'trust_audit.user_id'),
('funzione', '_chain_participant_exists'),
('funzione', '_norm'),
('funzione', '_test_dollar'),
('funzione', 'accept_offer'),
('funzione', 'accept_offer_any'),
('funzione', 'accept_terms'),
('funzione', 'account_deletion_blockers'),
('funzione', 'after_insert_offers_update_listing'),
('funzione', 'after_update_listings_invalidate_translations'),
('funzione', 'after_update_offers_propagate'),
('funzione', 'anonymize_account'),
('funzione', 'answer_listing_question'),
('funzione', 'before_insert_listing_images_enforce'),
('funzione', 'before_insert_listings_block_duplicate'),
('funzione', 'before_insert_offers_enforce'),
('funzione', 'before_update_listings_invalidate_trust'),
('funzione', 'before_update_listings_lock_columns'),
('funzione', 'before_update_listings_lock_terminal'),
('funzione', 'cancel_accepted_offer_any'),
('funzione', 'confirm_chain_participant'),
('funzione', 'confirm_exchange_any'),
('funzione', 'create_chain_proposal'),
('funzione', 'declare_payment'),
('funzione', 'decline_chain_participant'),
('funzione', 'decline_offer'),
('funzione', 'decline_offer_any'),
('funzione', 'enforce_active_listing_cap'),
('funzione', 'expire_my_stale_listings'),
('funzione', 'expire_old_accepted_offers'),
('funzione', 'expire_old_chain_proposals'),
('funzione', 'expire_old_listings'),
('funzione', 'expire_old_offers'),
('funzione', 'finalize_offer_any'),
('funzione', 'fn_user_top_matches'),
('funzione', 'get_my_pending_offer_any'),
('funzione', 'get_offer_handshake'),
('funzione', 'get_payment_declarations'),
('funzione', 'get_user_rating'),
('funzione', 'handle_new_user'),
('funzione', 'is_pnr_active'),
('funzione', 'list_incoming_offers_any'),
('funzione', 'list_listing_questions'),
('funzione', 'list_my_active_listings'),
('funzione', 'list_my_chain_chats'),
('funzione', 'list_my_chats'),
('funzione', 'list_my_listings_pending_trust'),
('funzione', 'list_my_pending_questions'),
('funzione', 'list_outgoing_offers_any'),
('funzione', 'mark_chain_chat_read'),
('funzione', 'mark_chat_read'),
('funzione', 'mark_my_resolved_offers_seen'),
('funzione', 'mark_offer_unseen_on_resolution'),
('funzione', 'my_offer_role'),
('funzione', 'my_rating_for_chain'),
('funzione', 'my_rating_for_offer'),
('funzione', 'notify_on_chain_canceled'),
('funzione', 'notify_on_offer'),
('funzione', 'on_listing_status_change'),
('funzione', 'pnr_fingerprint'),
('funzione', 'pnr_is_plausible'),
('funzione', 'rate_chain_transaction'),
('funzione', 'rate_transaction'),
('funzione', 'recompute_listing_pending_state'),
('funzione', 'refresh_profile_counters'),
('funzione', 'release_all_stale_reservations'),
('funzione', 'release_my_stale_reservations'),
('funzione', 'remind_pending_confirmations'),
('funzione', 'remind_pending_ratings'),
('funzione', 'remind_stale_chain_confirmers'),
('funzione', 'replace_matches_for_sources'),
('funzione', 'report_chain_problem'),
('funzione', 'report_exchange_problem'),
('funzione', 'resolve_chain_dispute'),
('funzione', 'resolve_exchange_dispute'),
('funzione', 'set_updated_at'),
('funzione', 'sync_email_verified'),
('funzione', 'sync_pnr_fingerprint'),
('funzione', 'update_listing_trust_score'),
('trigger',  'after_chain_proposal_canceled'),
('trigger',  'after_offer_notify'),
('trigger',  'on_auth_user_created'),
('trigger',  'on_auth_user_email_confirmed'),
('trigger',  'set_offers_updated_at'),
('trigger',  'trg_after_insert_offers_update_listing'),
('trigger',  'trg_after_update_offers_propagate'),
('trigger',  'trg_before_insert_offers_enforce'),
('trigger',  'trg_listing_images_max_two'),
('trigger',  'trg_listing_secrets_fingerprint'),
('trigger',  'trg_listings_active_cap'),
('trigger',  'trg_listings_block_duplicate'),
('trigger',  'trg_listings_counters'),
('trigger',  'trg_listings_invalidate_translations'),
('trigger',  'trg_listings_lock_columns'),
('trigger',  'trg_listings_lock_terminal'),
('trigger',  'trg_listings_trust_invalidate'),
('trigger',  'trg_listings_updated_at'),
('trigger',  'trg_offers_mark_unseen'),
('trigger',  'trg_update_listing_trust_score')
)
SELECT tipo, oggetto AS manca
FROM attesi a
WHERE NOT CASE a.tipo
  WHEN 'tabella' THEN to_regclass('public.' || a.oggetto) IS NOT NULL

  WHEN 'colonna' THEN
    -- assente = manca DAVVERO la colonna, non l'intera tabella
    to_regclass('public.' || split_part(a.oggetto, '.', 1)) IS NULL
    OR EXISTS (
      SELECT 1 FROM information_schema.columns c
      WHERE c.table_schema = 'public'
        AND c.table_name = split_part(a.oggetto, '.', 1)
        AND c.column_name = split_part(a.oggetto, '.', 2)
    )

  WHEN 'funzione' THEN EXISTS (
    SELECT 1 FROM pg_proc p
    JOIN pg_namespace n ON n.oid = p.pronamespace
    WHERE n.nspname = 'public' AND p.proname = a.oggetto
  )

  WHEN 'trigger' THEN EXISTS (
    SELECT 1 FROM pg_trigger t
    WHERE NOT t.tgisinternal AND t.tgname = a.oggetto
  )

  ELSE true
END
ORDER BY tipo, oggetto;
